/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3dModelFirst.glb -o src/Model.jsx --transform 
Files: public/3dModelFirst.glb [7.17MB] > C:\Users\joani\Documents\porfolio\porfolio\src\3dModelFirst-transformed.glb [839.12KB] (88%)
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('3dModelFirst-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="pilono_estatua_037" position={[12.503, 10.592, 36.107]} scale={0.025} />
        <group name="pilono_estatua_038" position={[12.503, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <group name="pilono_estatua_041" position={[12.505, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <group name="pilono_estatua_043" position={[12.505, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_02" geometry={nodes.pilono_estatua_02.geometry} material={materials.Escultura_Faraon} position={[-11.997, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_053" geometry={nodes.pilono_estatua_053.geometry} material={materials.Escultura_Faraon} position={[12.506, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="sala_hipostila_detalle001" geometry={nodes.sala_hipostila_detalle001.geometry} material={materials.Sala_Hipostila} position={[4.753, 17.447, -2.892]} rotation={[Math.PI / 2, 0, 0]} scale={0.053} />
        <mesh name="pilono_estatua_034" geometry={nodes.pilono_estatua_034.geometry} material={materials.Sala_Pilonos} position={[23.827, 6.784, 42.546]} rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.025} />
        <mesh name="jarron_011_OK" geometry={nodes.jarron_011_OK.geometry} material={materials.Jarrones} position={[3.76, 0.162, -4.846]} scale={0.018} />
        <mesh name="Box022" geometry={nodes.Box022.geometry} material={materials.Sala_Santuario} position={[0.105, 0.228, -25.403]} scale={0.027} />
        <mesh name="sala_santuario_detalle_03" geometry={nodes.sala_santuario_detalle_03.geometry} material={materials.Detalles_Extra} position={[3.459, 0.457, -28.225]} scale={0.027} />
        <mesh name="pilono_estatua_00" geometry={nodes.pilono_estatua_00.geometry} material={materials.Escultura_Faraon} position={[-11.997, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_044" geometry={nodes.pilono_estatua_044.geometry} material={materials.Escultura_Faraon} position={[12.506, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_07" geometry={nodes.pilono_estatua_07.geometry} material={materials.Escultura_Faraon} position={[-11.997, 6.879, 38.236]} scale={0.025} />
        <mesh name="pilono_estatua_049" geometry={nodes.pilono_estatua_049.geometry} material={materials.Escultura_Faraon} position={[12.506, 6.879, 38.236]} scale={0.025} />
        <mesh name="pilono_estatua_06" geometry={nodes.pilono_estatua_06.geometry} material={materials.Escultura_Faraon} position={[-12.013, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_048" geometry={nodes.pilono_estatua_048.geometry} material={materials.Escultura_Faraon} position={[12.491, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_09" geometry={nodes.pilono_estatua_09.geometry} material={materials.Escultura_Faraon} position={[-11.996, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_051" geometry={nodes.pilono_estatua_051.geometry} material={materials.Escultura_Faraon} position={[12.508, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_01" geometry={nodes.pilono_estatua_01.geometry} material={materials.Escultura_Faraon} position={[-12.156, 12.191, 36.826]} rotation={[Math.PI / 2, 0, 0]} scale={0.025} />
        <mesh name="pilono_estatua_13" geometry={nodes.pilono_estatua_13.geometry} material={materials.Detalles_Extra} position={[-11.996, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_052" geometry={nodes.pilono_estatua_052.geometry} material={materials.Detalles_Extra} position={[12.508, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_03" geometry={nodes.pilono_estatua_03.geometry} material={materials.Detalles_Extra} position={[-11.997, 10.592, 36.107]} scale={0.025} />
        <mesh name="pilono_estatua_046" geometry={nodes.pilono_estatua_046.geometry} material={materials.Detalles_Extra} position={[12.507, 10.592, 36.107]} scale={0.025} />
        <mesh name="pilono_estatua_05" geometry={nodes.pilono_estatua_05.geometry} material={materials.Detalles_Extra} position={[-11.997, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_047" geometry={nodes.pilono_estatua_047.geometry} material={materials.Detalles_Extra} position={[12.506, 10.734, 37.158]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_08" geometry={nodes.pilono_estatua_08.geometry} material={materials.Detalles_Extra} position={[-11.996, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="pilono_estatua_050" geometry={nodes.pilono_estatua_050.geometry} material={materials.Detalles_Extra} position={[12.508, 8.612, 34.275]} rotation={[Math.PI / 2, 0, 0]} scale={0.213} />
        <mesh name="sala_hipetra_izq" geometry={nodes.sala_hipetra_izq.geometry} material={materials.Sala_Muralla} position={[-9.01, 0.06, 17.662]} scale={0.053} />
        <mesh name="sala_hipetra_izq_columna_00" geometry={nodes.sala_hipetra_izq_columna_00.geometry} material={materials.Columnas} position={[-5.794, 6.58, 8.755]} rotation={[0, -Math.PI / 4, 0]} scale={0.053} />
        <mesh name="escaleras" geometry={nodes.escaleras.geometry} material={materials.Suelo} position={[0.027, -0.052, -9.188]} scale={0.025} />
      </group>
    </group>
  )
}

useGLTF.preload('3dModelFirst-transformed.glb')
